[package]
name = "cw"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.42", features = ["derive"] }
dialoguer = "0.11.0"
dirs = "6.0.0"
git2 = "0.20.2"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
toml = "0.9.4"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
